# This rule is not used by the project kube-nova-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to apps.ikubeops.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-nova-operator
    app.kubernetes.io/managed-by: kustomize
  name: kubenova-viewer-role
rules:
- apiGroups:
  - apps.ikubeops.com
  resources:
  - kubenova
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.ikubeops.com
  resources:
  - kubenova/status
  verbs:
  - get
