apiVersion: apps.ikubeops.com/v1
kind: KubeNova
metadata:
  labels:
    app.kubernetes.io/name: kube-nova-operator
    app.kubernetes.io/managed-by: kustomize
  name: kubenova-sample
spec:
  # TODO(user): Add fields here
